### ISSUE TITLE
running install to create my own image from fresh alpine linux lx zone shows error

### ISSUE THREAD

**Issue by razamatan** [joyent/alpine-lx-brand-image-builder#1]
created an alpine lx zone:

> d8830f1e-3680-11e6-be72-2ba188e02d31  alpine-3     20160620  linux    lx-dataset    2016-06-20

then i ran the install script from there:

> ./install -r 3.4 -a apk-tools-static-2.6.7-r0.apk -d /data/alpine -m http://mirrors.gigenet.com/alpinelinux/ -i alpine-3 -p "Alpine Linux" -D "Alpine 3.4.1 64-bit lx-brand image." -u https://docs.joyent.com/images/container-native-linux

but it fails w/ exit code 4 on the `===> Installing Alpine base step`:

> (1/16) Installing musl (1.1.14-r10)
> (2/16) Installing busybox (1.24.2-r9)
> Executing busybox-1.24.2-r9.post-install
> /native/usr/lib/amd64/lx_brand.so.1: not found.ERROR: busybox-1.24.2-r9.post-install: script exited wi
> th error 1
> (3/16) Installing alpine-baselayout (3.0.3-r0)
> Executing alpine-baselayout-3.0.3-r0.pre-install
> /native/usr/lib/amd64/lx_brand.so.1: not found.ERROR: alpine-baselayout-3.0.3-r0.pre-install: script e
> xited with error 1
> Executing alpine-baselayout-3.0.3-r0.post-install
> /native/usr/lib/amd64/lx_brand.so.1: not found.ERROR: alpine-baselayout-3.0.3-r0.post-install: script 
> exited with error 1
> (4/16) Installing openrc (0.21-r0)
> Executing openrc-0.21-r0.post-install
> /native/usr/lib/amd64/lx_brand.so.1: not found.ERROR: openrc-0.21-r0.post-install: script exited with 
> error 1
> (5/16) Installing alpine-conf (3.4.1-r0)
> (6/16) Installing zlib (1.2.8-r2)
> (7/16) Installing libcrypto1.0 (1.0.2h-r1)
> (8/16) Installing libssl1.0 (1.0.2h-r1)
> (9/16) Installing apk-tools (2.6.7-r0)
> (10/16) Installing busybox-suid (1.24.2-r9)
> (11/16) Installing busybox-initscripts (3.0-r2)
> Executing busybox-initscripts-3.0-r2.post-install
> /native/usr/lib/amd64/lx_brand.so.1: not found.ERROR: busybox-initscripts-3.0-r2.post-install: script 
> exited with error 1
> (12/16) Installing scanelf (1.1.6-r0)
> (13/16) Installing musl-utils (1.1.14-r10)
> (14/16) Installing libc-utils (0.7-r0)
> (15/16) Installing alpine-keys (1.1-r0)
> (16/16) Installing alpine-base (3.4.1-r0)
> Executing busybox-1.24.2-r9.trigger
> /native/usr/lib/amd64/lx_brand.so.1: not found.ERROR: busybox-1.24.2-r9.trigger: script exited with er
> ror 1
> 4 errors; 7 MiB in 16 packages

i've tried symlinking /native into /data/alpine in the script before this stage, but it didn't work.

how do i get past this?

**Comment by chorrell** [comment]
Hi!

I usually build the image on a CentOS KVM instance. Building on lx-brand isn't something that has been tested or supported and it's probably why you are having issues, sorry.

**Comment by razamatan** [comment]
is there a way i can fix it?

i took this line in the readme:

> Alpine, Ubuntu or CentOS running in a VM or bare metal (required for the install script)
> as "bare metal" == lx zone, what with zones referred to as "bare metal" in joyent so much.

**Comment by chorrell** [comment]
I don't really know, I've never tried building on lx-brand Alpine before. I'm not even sure if it's possible. 

I can update the README to be more clear.
